### ISSUE TITLE
pcall return value

### ISSUE THREAD

**Issue by lambage** [OldFisher/lua-api-pp#7]
I'm using visual studio 2015 (msbuild) and having an issue with wrapping function calls.  

I have a function that looks like this:

`GetMethodFromModule(module_name, method_name).pcall(std::forward<Args>(args)...);`

How do I actually check for an error, pcall returns a lazy, and I've tried explicitly setting it to a lua::Value but it doesn't seem to give me what I want.

I can do 

`auto error = GetMethodFromModule(module_name, method_name).pcall(std::forward<Args>(args)...).cast<std::string>();`

But then I'll get a bad cast if there is no error.

Any suggestions of how to get the error out of the pcall method?

**Comment by lambage** [comment]
Okay I got it.

```
auto fn = GetMethodFromModule(module_name, method_name);

if (fn.is<lua::LFunction>())
{
     lua::Valset result = fn.pcall(std::forward<Args>(args)...);
     if (!result.success())
     {
         throw std::runtime_error(result[0].cast<std::string>());
     }
}
```

**Comment by OldFisher** [comment]
Yes, that is how it is done.
